trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    pwd
    ls -ltr
    find . -name "*.tf"
  displayName: 'Verify Terraform Files'

- script: |
    terraform version
  displayName: 'Check Terraform'